import {
  Injectable,
  UnauthorizedException,
  BadRequestException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { randomBytes, timingSafeEqual } from 'crypto';
import type { Request } from 'express';
import { GameSettings } from '../entities/game-settings.entity';

/** Mobil kliens fejléc; az Android app minden releváns kérésnél küldi, ha a szerver megköveteli. */
export const MOBILE_ENROLLMENT_HEADER = 'x-ck-enrollment-secret';

export type AdminMobileConnectionDto = {
  apiBaseUrl: string;
  enrollmentEnabled: boolean;
  enrollmentSecret: string;
  /** Ha true, a titok a .env-ből jön — az admin UI nem generálhat újat. */
  enrollmentSecretFromEnv: boolean;
};

@Injectable()
export class MobileEnrollmentService {
  constructor(
    private readonly config: ConfigService,
    @InjectRepository(GameSettings)
    private readonly gameSettingsRepository: Repository<GameSettings>,
  ) {}

  private readEnvSecret(): string | null {
    const v = this.config.get<string>('MOBILE_ENROLLMENT_SECRET');
    const t = String(v ?? '').trim();
    return t.length > 0 ? t : null;
  }

  private async ensureGameSettingsRow(): Promise<GameSettings> {
    const rows = await this.gameSettingsRepository.find({
      order: { id: 'ASC' },
    });
    let row = rows[0];
    if (!row) {
      row = this.gameSettingsRepository.create({
        gameEnabled: false,
        locationUpdateIntervalMinutes: 20,
        stayRuleEnabled: false,
        stayRadiusKm: 5,
        mobileEnrollmentSecret: null,
      });
      row = await this.gameSettingsRepository.save(row);
      return row;
    }

    // Self-heal: a tábla singletonként működik, ezért duplikátum esetén
    // az első sort tartjuk meg, és (ha kell) átemeljük a meglévő mobil secretet.
    if (rows.length > 1) {
      if (!row.mobileEnrollmentSecret?.trim()) {
        const nonEmptySecretRow = rows.find((r) => r.mobileEnrollmentSecret?.trim());
        if (nonEmptySecretRow?.mobileEnrollmentSecret?.trim()) {
          row.mobileEnrollmentSecret = nonEmptySecretRow.mobileEnrollmentSecret.trim();
          row = await this.gameSettingsRepository.save(row);
        }
      }
      const duplicateIds = rows.slice(1).map((r) => r.id);
      if (duplicateIds.length > 0) {
        await this.gameSettingsRepository.delete(duplicateIds);
      }
    }
    return row;
  }

  /** Első admin megtekintéskor: ha nincs .env titok, generálunk egyet az adatbázisba. */
  async ensureAutoGeneratedSecretInDbIfNeeded(): Promise<void> {
    if (this.readEnvSecret()) return;
    const row = await this.ensureGameSettingsRow();
    if (!row.mobileEnrollmentSecret?.trim()) {
      row.mobileEnrollmentSecret = randomBytes(32).toString('base64url');
      await this.gameSettingsRepository.save(row);
    }
  }

  async getEffectiveSecret(): Promise<string | null> {
    const env = this.readEnvSecret();
    if (env) return env;
    const row = await this.gameSettingsRepository.findOne({
      where: {},
      order: { id: 'ASC' },
    });
    const db = row?.mobileEnrollmentSecret?.trim();
    return db && db.length > 0 ? db : null;
  }

  async isEnforcementEnabled(): Promise<boolean> {
    return (await this.getEffectiveSecret()) != null;
  }

  extractProvidedSecret(headers: Record<string, string | string[] | undefined>): string {
    const raw =
      headers[MOBILE_ENROLLMENT_HEADER] ??
      headers['x-ck-enrollment-secret'];
    if (Array.isArray(raw)) return String(raw[0] ?? '').trim();
    return String(raw ?? '').trim();
  }

  async assertValidEnrollmentHeader(req: {
    headers: Record<string, string | string[] | undefined>;
  }): Promise<void> {
    const expected = await this.getEffectiveSecret();
    if (!expected) return;
    const provided = this.extractProvidedSecret(req.headers);
    if (!this.timingSafeEqualStrings(provided, expected)) {
      throw new UnauthorizedException('Érvénytelen mobil kapcsolódási titok');
    }
  }

  async verifyForPublicPing(req: {
    headers: Record<string, string | string[] | undefined>;
  }): Promise<{
    ok: true;
    enrollmentRequired: boolean;
  }> {
    const expected = await this.getEffectiveSecret();
    if (!expected) {
      return { ok: true, enrollmentRequired: false };
    }
    const provided = this.extractProvidedSecret(req.headers);
    if (!this.timingSafeEqualStrings(provided, expected)) {
      throw new UnauthorizedException('Érvénytelen mobil kapcsolódási titok');
    }
    return { ok: true, enrollmentRequired: true };
  }

  async getAdminMobileConnectionDto(req: Request): Promise<AdminMobileConnectionDto> {
    await this.ensureAutoGeneratedSecretInDbIfNeeded();
    return this.buildAdminDto(req);
  }

  /**
   * Új véletlen titok az adatbázisban. A .env MOBILE_ENROLLMENT_SECRET beállításakor nem futtatható
   * (a titkot akkor kézzel / deploydal kell kezelni).
   */
  async regenerateEnrollmentSecret(req: Request): Promise<AdminMobileConnectionDto> {
    if (this.readEnvSecret()) {
      throw new BadRequestException(
        'A mobil titkot a MOBILE_ENROLLMENT_SECRET .env változó adja — új titok generálásához távolítsd el vagy ürítsd ki ezt a sort, majd használd az admin felület gombját.',
      );
    }
    const row = await this.ensureGameSettingsRow();
    row.mobileEnrollmentSecret = randomBytes(32).toString('base64url');
    await this.gameSettingsRepository.save(row);
    return this.buildAdminDto(req);
  }

  private async buildAdminDto(req: Request): Promise<AdminMobileConnectionDto> {
    const env = this.readEnvSecret();
    const secret = (await this.getEffectiveSecret()) ?? '';
    return {
      apiBaseUrl: this.buildPublicApiBaseUrl(req),
      enrollmentEnabled: secret.length > 0,
      enrollmentSecret: secret,
      enrollmentSecretFromEnv: !!env,
    };
  }

  buildPublicApiBaseUrl(req: Request): string {
    const fromEnv = this.config.get<string>('PUBLIC_API_BASE_URL')?.trim();
    if (fromEnv) {
      return this.normalizeTrailingSlash(fromEnv);
    }
    const xfProto = (req.headers['x-forwarded-proto'] as string | undefined)?.split(',')?.[0]?.trim();
    const proto = xfProto || (req.protocol as string) || 'http';
    const xfHost = (req.headers['x-forwarded-host'] as string | undefined)?.split(',')?.[0]?.trim();
    const host = xfHost || req.get('host') || 'localhost';
    return this.normalizeTrailingSlash(`${proto}://${host}`);
  }

  private normalizeTrailingSlash(base: string): string {
    const t = base.replace(/\s+$/, '').replace(/\/+$/, '');
    return `${t}/`;
  }

  private timingSafeEqualStrings(a: string, b: string): boolean {
    try {
      const ba = Buffer.from(a, 'utf8');
      const bb = Buffer.from(b, 'utf8');
      if (ba.length !== bb.length) return false;
      return timingSafeEqual(ba, bb);
    } catch {
      return false;
    }
  }
}
